name: mobilecapacityenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - gdal=3.3.3
  - geopandas=0.13.2
  - numpy=1.23.2
  - openpyxl=3.1.2
  - pandas=2.2.1
  - pandana=0.6.1
  - plotly=5.10.0
  - pycountry=22.3.5
  - pip=23.3.2
  - flake8=7.0.0 
  - autopep8=2.0.4 
  - pytest==7.4.0
  - pytest-cov==4.1.0
  - seaborn==0.13.2
  - ipykernel==6.25.0
  - jupyterlab==4.1.1
  - scikit-learn==1.1.2
  - scipy==1.9.1
  - tqdm==4.64.0
  - pyyaml==6.0.1
  - flake8-junit-report==2.1.0
  - python-dotenv==1.0.1
  - pip=23.3.2
  - pip:
    - python-srtm==0.5.
    - shapely==2.0.2
    - rasterio==1.3.8
    - rasterstats==0.20.0
    - osmnx==1.7.0