name: mobilecapacityenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - geopandas
  - matplotlib
  - numpy>=1.21.0
  - flake8
  - autopep8
  - pandas
  - rasterio
  - rasterstats=0.19.0
  - scipy
  - folium
  - shapely
  - pytest
  - streamlit
  - nbstripout
  - nbconvert
  - contextily=1.6.2
  - flake8-junit-report=2.1.0
  - python-dotenv==1.0.1
  - pytest-cov=4.1.0
  - pip:
    - python-srtm==0.5.0
    - cryptography==43.0.1