name: mobilecapacityenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - geopandas
  - matplotlib
  - numpy>=1.21.0
  - flake8
  - autopep8
  - pandas
  - rasterio
  - rasterstats=0.19.0
  - scipy
  - shapely
  - pytest
  - streamlit
  - nbstripout
  - nbconvert
  - flake8-junit-report=2.1.0
  - python-dotenv==1.0.1
  - pytest-cov=4.1.0